### ISSUE TITLE
Deviating versions of oemof.db in pip and git

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#14]
Latest version Tag of oemof.db in git is 0.0.3 whereas latest pip version of oemof.db is 0.0.2.

I assumed both versions should be the same. Is this assumption right?

**Comment by uvchik** [comment]
I do not think that there is a pip version of oemof.db. At least I cannot find one. Maybe you have local version on your system. 

But it is a good idea to create one :+1: 

I agree that the version numbering should be consistently :smile:

**Comment by gplssm** [comment]
Yep, you're right. There is just a local installation from the git repo.

Does it make sense to release the current version on pip or should we do some work before and define a new version before?

**Comment by uvchik** [comment]
I would release the actual dev as version v0.0.4 and publish it on pypi. If anybody wants anything else he/she can do it with v0.0.5.
