### ISSUE TITLE
How to handle failing shapely installation?

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#16]
Installation of oemof.db requires the package shapely to be installed. The installation of shapely via pip3 fails with following message

```
OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
```

Available solutions (Workarounds)
- For Linux: `sudo apt-get install libgeos-dev`
- Windows: _please add if you know about_ (it was something with the installation of libgeos from pre-built binary package)

This enables us to regularly install shapely via `pip3 install shapely`.

How can we automize this solution/workaround to enable new users to smoothly install oemof.db?

**Comment by uvchik** [comment]
Shapely is no longer a requirement of oemof.db.
