### ISSUE TITLE
Ask for password entry if password isn't available in keyring

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#22]
Currently, if a database connection is established with the help of oemof.db and the password isn't available in the keyring, program crashes. Make this more convenient by

1. Ask for password entry if password isn't available in keyring
2. Exit program early with information about missing password and provide help to the user how to add the password to the keyring

**Comment by uvchik** [comment]
At the moment it is also possible to add the password to the config file, but I'm not sure if we want to support such an unsecure way.

**Comment by gplssm** [comment]
Suggestion by @uvchik: take some graphical input method, if possible cross-platform and without struggle. Maybe postpone it to later versions

**Comment by uvchik** [comment]
A graphical input should always be optional to avoid additional requirements. This is just nice to have. Are you going to add the "input on demand" via terminal?

**Comment by gplssm** [comment]
I did it in #25. If you, @uvchik, find time for a short review, I would really appreciate!
