### ISSUE TITLE
Create default config file

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#23]
This can be done either

1. at installation oemof.db
2. at program start if config file does not exists

Following aspects would improve this
* Ask the user if he/she wants to create the config file
* Ask for the location of config file and provide default location
* Warn about overwriting an existing config file

**Comment by uvchik** [comment]
How do you want to ask the user?

**Comment by gplssm** [comment]
Haven't specified this. I thought of something like using input(). Any recommendations/comments on this?

**Comment by gplssm** [comment]
Results from a call with @uvchik

We agreed on
* Methods like `db.connection()` get an additional kwarg called `configfile`
* oemof.db checks for config file at each call of methods/functions that rely on the config file
* If the config file does not exists, it will be created at specified or default location
* Programs exits after config file creation and prompts user to edit config according to his/her needs
* Logging is used to communicate with the user

Open Questions

1. Which other functions depend on a config file and have to be treatened like `db.connection()`?
2. If there are a plenty of functions that use the config file, I may would be wise to implement variable config file location and automatic creation of config file in a more general way to cover all functions in oemof.db with is.

**Comment by gplssm** [comment]
Decided to just inform the user and give advice how the config file's format looks like.
