### ISSUE TITLE
Release 0.0.4 is planned for Friday 16th

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#24]
For a pre-release on Dingo we need some additional options in oemof.db that necessitates a new release.
Therefore, I create a  [list a additions](https://github.com/oemof/oemof.db/milestone/2) I would to implement. Feel free to add yours!

**Comment by gplssm** [comment]
Done

**Comment by uvchik** [comment]
Thank you for you work. I had a brief look at your changes. Looks good.

I guess in the readme you want to install `oemof.db` and not `oemof`?
