### ISSUE TITLE
Remember to merge changes in the master branch back into dev

### ISSUE THREAD

**Issue by cswh** [oemof/oemof_pg#5]
@oemof/oemof-main  
Remember to merge changes in the master branch (hotfixes or direct changes on the master branch itself) back into dev.
see http://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches

**Comment by uvchik** [comment]
I haven't created a `dev branch` and I haven't commited on a `dev branch`.

**Comment by cswh** [comment]
But Cord has started a dev branch in December and you have made a commit on the master branch since then.

**Comment by uvchik** [comment]
Didn't see it. Forgot to fetch. Shame on me.
