### ISSUE TITLE
Adapt namespace from dev to master branch

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#6]
Namespaces of dev and master branch are different. In order to avoid confusion it would be helpful to align these both. For example name folder oemof_pg to oemof. This would enable user to run two_regions_example_opt.py with checked out master branch of oemof.db.

**Comment by uvchik** [comment]
@cswh Can you do it together with the next release?

**Comment by cswh** [comment]
I think there was some progess, wasn't it? Does it work now?

**Comment by gnn** [comment]
The wasn't much to do. I merged the current status of `dev` into `master` and tagged the release. As @uvchik already changed the default branch to `dev` everything should be working as expected now. I'll assign @gplssm for last sanity checks. You can close this issue if everything is ok now.

**Comment by gplssm** [comment]
Everything is fine now! (:
